# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-25 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=200)),
                ('commodity_info', models.TextField()),
                ('remained_count', models.IntegerField(default=0)),
                ('cost_per_item', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_delivery', models.BooleanField()),
                ('total_cost', models.FloatField()),
                ('creation_time', models.DateTimeField()),
                ('delivery_completion_time', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=150)),
                ('order_status', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cost_per_one', models.FloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalFeed.Commodity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalFeed.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalFeed.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
